// Simple array extracted from the provided Word doc (one item per entry)
const PETROLUM_LIST = [
"Adhesive",
"Air mattresses",
"Ammonia",
"Antifreeze",
"Antihistamines",
"Antiseptics",
"Artificial limbs",
"Artificial turf",
"Asphalt",
"Aspirin",
"Awnings",
"Backpacks",
"Balloons",
"Ballpoint pens",
"Bandages",
"Beach umbrellas",
"Boats",
"Cameras",
"Candies and gum",
"Candles",
"Car battery cases",
"Car enamel",
"Cassettes",
"Caulking",
"CDs/computer disks",
"Cell phones",
"Clothes",
"Clothesline",
"Clothing",
"Coffee makers",
"Cold cream",
"Combs",
"Computer keyboards",
"Computer monitors",
"Cortisone",
"Crayons",
"Credit cards",
"Curtains",
"Dashboards",
"Denture adhesives",
"Dentures",
"Deodorant",
"Detergent",
"Dice",
"Dishwashing liquid",
"Dog collars",
"Drinking cups",
"Dyes",
"Electric blankets",
"Electrical tape",
"Enamel",
"Epoxy paint",
"Eyeglasses",
"Fan belts",
"Faucet washers",
"Fertilizers",
"Fishing boots",
"Fishing lures",
"Floor wax",
"Food preservatives",
"Footballs",
"Fuel tanks",
"Glue",
"Glycerin",
"Golf bags",
"Golf balls",
"Guitar strings",
"Hair coloring",
"Hair curlers",
"Hand lotion",
"Hearing aids",
"Heart valves",
"House paint",
"Hula hoops",
"Ice buckets",
"Ice chests",
"Ice cube trays",
"Ink",
"Insect repellent",
"Insecticides",
"Insulation",
"iPad/iPhone",
"Kayaks",
"Laptops",
"Life jackets",
"Light-weight aircraft",
"Lipstick",
"Loudspeakers",
"Lubricants",
"Luggage",
"Model cars",
"Mops",
"Motorcycle helmets",
"Movie film",
"Nail polish",
"Noise insulation",
"Nylon rope",
"Oil filters",
"Packaging",
"Paint brushes",
"Paint roller",
"Pajamas",
"Panty hose",
"Parachutes",
"Perfumes",
"Permanent press",
"Petroleum jelly",
"Pharmaceuticals",
"Pillow filling",
"Plastic toys",
"Plastics",
"Plywood adhesive",
"Propane",
"Purses",
"Putty",
"Refrigerants",
"Refrigerator linings",
"Roller skate wheels",
"Roofing",
"Rubber cement",
"Rubbing alcohol",
"Safety glasses",
"Shampoo",
"Shaving cream",
"Shoe polish",
"Shoes/sandals",
"Shower curtains",
"Skateboards",
"Skis",
"Soap dishes",
"Soft contact lenses",
"Solar panels",
"Solvents",
"Spacesuits",
"Sports car bodies",
"Sunglasses",
"Surf boards",
"Swimming pools",
"Synthetic rubber",
"Telephones",
"Tennis rackets",
"Tents",
"Tires",
"Tool boxes",
"Tool racks",
"Toothbrushes",
"Toothpaste",
"Transparent tape",
"Trash bags",
"Truck and automobile parts",
"Tubing",
"TV cabinets",
"Umbrellas",
"Unbreakable dishes",
"Upholstery",
"Vaporizers",
"Vinyl flooring",
"Vitamin capsules",
"Water pipes",
"Wind turbine blades",
"Yarn"
];

// Export for simple inclusion in pages (browser global)
